name: build full release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      hb_tag:
        description: 'Version Tag'
        default: '1.9.0'
        required: true
  create:
    tags:
      - '*'

env:
  HB_TAG: ${{ github.event.inputs.hb_tag }}

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os-version: ["trixie", "bookworm", "bullseye", "noble", "jammy", "focal"]
    container:
      image: "ghcr.io/${{ github.repository_owner }}/handbrake-custom-build:${{ matrix.os-version }}"
      options: --privileged --device /dev/fuse
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set env
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "HB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set env
        if: github.event.inputs.hb_tag != ''
        run: echo "HB_TAG=${{ github.event.inputs.hb_tag }}" >> $GITHUB_ENV
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            cache
          key: "${{ matrix.os-version }}-build-cache-${{ env.HB_TAG }}"
          restore-keys: |
            "${{ matrix.os-version }}-build-cache-"
      - name: Run build script
        run: ./scripts/build.sh
        env:
          DEB_FLAVOR: "${{ matrix.os-version }}"
      - name: Cache build
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            cache
          key: "${{ matrix.os-version }}-build-cache-${{ env.HB_TAG }}"
      - name: Upload deb files
        uses: actions/upload-artifact@v4
        with:
          name: "packages-${{ env.HB_TAG }}-${{ matrix.os-version }}"
          path: ./*.deb

  merge-artefacts:
    name: Merge all deb files to single artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: debian-packages
        uses: actions/upload-artifact/merge@v4

  add_release:
    name: Add package to release
    needs: merge-artefacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: merged-artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.deb

  add_repo:
    name: Add packages to public debian repository
    runs-on: ubuntu-latest
    needs: merge-artefacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "merged-artifacts"
      - name: Add releases to repo
        uses: smeinecke/apt-repo-action@v2.1.6
        with:
          github_token: ${{ github.token }}
          repo_supported_arch: |
            amd64
          repo_supported_version: |
            bullseye
            bookworm
            focal
            jammy
            noble
          file: |
            *.deb
          version_by_filename: true
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
