name: build all docker images

on:
  workflow_dispatch:


env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os-version:
          - 'trixie'
          - 'bookworm'
          - 'bullseye'
          - 'noble'
          - 'jammy'
          - 'focal'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker"
          file: "build-${{ matrix.os-version }}.Dockerfile"
          push: true
          tags: "${{ env.REGISTRY }}/${{ github.repository_owner }}/handbrake-custom-build:${{ matrix.os-version }}"
